name: wisdom
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  build_runner: ^2.1.5
  get_it: ^7.2.0
  flutter_svg: ^1.0.0
  shared_preferences: ^2.0.11
  package_info_plus: ^1.3.0
  flutter_sticky_header: ^0.6.0
  pull_to_refresh: ^2.0.0
  loading_indicator: ^3.0.2
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  device_info: ^2.0.3
  retrofit: ^3.0.1
  dio: ^4.0.4
  retrofit_generator: ^3.0.1+1
  pretty_dio_logger: ^1.1.1
  lottie: ^1.2.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/jsons/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          #- asset: assets/fonts/Poppins/Poppins-Medium.ttf
          #weight: 600
          #- asset: assets/fonts/Poppins-Bold.ttf
          #weight: 700

    - family: MyanUni
      fonts:
        - asset: assets/fonts/MyanUni/pds_regular.ttf